steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:latest', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'servipal-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-secrets=/secrets/.env=Servi-pal-secret:latest'
      - '--memory=1Gi'
      - '--timeout=300'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:latest'






# steps:
#   # 1. Run Tests
#   - name: 'python:3.12-slim'
#     entrypoint: 'sh'
#     args:
#       - '-c'
#       - |
#         pip install uv
#         uv sync --frozen --dev
#         uv run pytest
#     env:
#       - 'ENVIRONMENT=test'
#       - 'SUPABASE_URL=https://mock.supabase.co'
#       - 'SUPABASE_KEY=mock-key'

#   # 2. Build the container image (Tagged with _COMMIT_SHA and latest)
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'build'
#       - '-t'
#       - 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:$_COMMIT_SHA'
#       - '-t'
#       - 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:latest'
#       - '.'

#   # 3. Deploy container image to Cloud Run
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: gcloud
#     args:
#       - 'run'
#       - 'deploy'
#       - 'servipal-backend'
#       - '--image'
#       - 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:$_COMMIT_SHA'
#       - '--region'
#       - 'us-central1'
#       - '--platform'
#       - 'managed'
#       - '--allow-unauthenticated'
#       - '--set-env-vars=ENVIRONMENT=production'
#       - '--set-secrets=/secrets/.env=Servi-pal-secret:latest'
#       - '--memory=1Gi'
#       - '--timeout=300'

# images:
#   - 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:$_COMMIT_SHA'
#   - 'us-central1-docker.pkg.dev/$PROJECT_ID/servipal-repo/servipal-backend:latest'

# substitutions:
#   _COMMIT_SHA: 'latest'
